### ISSUE TITLE
[BUG] 모달창 z-index 오류

### ISSUE THREAD

**Issue by juhee067** [petD-ary/petDiary#21]
### 버그
- 모달창 위로 input이 뜹니다!

### 버그 발생 지점

1. 반려동물 정보 입력으로 가서
2. 품종선택을 선택하고
3. 모달을 스크롤하면
4. 문제가 생깁니다.

### 스크린샷
<img width="806" alt="image" src="https://github.com/petD-ary/petDiary/assets/66045537/ab2fe831-917b-4ea4-a025-c18c5ad64f19">

모달창 밖을 스크롤해도 밖이 스크롤 됩니다!

**Comment by Dorabang** [comment]
확인했습니다. 수정 후 PR 작성하겠습니다!
