### ISSUE TITLE
[BUG] CSS 수정 요청

### ISSUE THREAD

**Issue by Dorabang** [petD-ary/petDiary#63]
### 버그
- Header 및 NavBar

### 버그 발생 지점

- [x] Header 
- [x] bottomNavBar

- Header 및 bottomNavBar CSS 수정 부탁드립니다.
  - 모바일 버전으로 확인 시 padding, font-size 등 잘못된 부분이 있어보여 요청드립니다! @catca @juhee067 

### 스크린샷
![image](https://github.com/petD-ary/petDiary/assets/39180932/2581e223-aa5d-4738-927b-6b4afffdc3e8)

**Comment by juhee067** [comment]
header 수정완료 했습니다.
<img width="759" alt="image" src="https://github.com/petD-ary/petDiary/assets/66045537/d03e3390-7ec1-4537-897d-16287b52d6bb">
